FROM minideb-kr:latest

MAINTAINER "lannerkr@gmail.com"

COPY ./ldap-db-server-v1.4 /usr/local/bin

WORKDIR /mnt/src

ENTRYPOINT [ "ldap-db-server-v1.4", "/mnt/src/conf.json" ]

##VOLUME ["/home/physis/golang/src/go/ldap-db-server/docker-image", "/mnt/src" ]

LABEL description="This is ldap to radius proxy server, + write user login history to mongodb"
